server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: hrms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
        slf4j:
          enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin

  # 缓存配置
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
#      timeout: 10000
#      lettuce:
#        pool:
#          max-active: 8
#          max-wait: -1
#          max-idle: 8
#          min-idle: 0

  # Flyway配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.lightereb.hrms.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true

# 日志配置
logging:
  level:
    root: info
    com.lightereb.hrms: debug
  file:
    name: logs/hrms.log

# JWT配置
jwt:
  secret: your-secret-key-here-should-be-at-least-256-bits
  expiration: 86400000
  header: Authorization
  token-prefix: Bearer

# Knife4j配置
knife4j:
  enable: true
  production: false